In [1]:
#Homework#1 Question3
import numpy as np
from numpy.linalg import inv
x = (0, 1, 2, 3, 4, 5 ,6 ,7 ,8 ,9, 10)
y = (4, 5, 16, 21, 36, 45, 64, 77, 100, 117, 144)
X=np.array([[1,x[0],x[0]**2],
            [1,x[1],x[1]**2],
            [1,x[2],x[2]**2],
            [1,x[3],x[3]**2],
            [1,x[4],x[4]**2],
            [1,x[5],x[5]**2],
            [1,x[6],x[6]**2],
            [1,x[7],x[7]**2],
            [1,x[8],x[8]**2],
            [1,x[9],x[9]**2],
            [1,x[10],x[10]**2]], dtype=np.float64)
Y=np.array([[y[0]],[y[1]],[y[2]],[y[3]],[y[4]],[y[5]],[y[6]],[y[7]],[y[8]],[y[9]], [y[10]]],dtype=np.float64)

#theta = (X.trans * X).reverse* X.tans*Y
XT=X.transpose()
print(XT)
a = np.dot(XT , X)
a = inv(a)
#print(a)

a = np.dot(a, XT)
#print(a)

a = np.dot(a, Y)
print("Theta is: \n", a)

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  0.   1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]]
Theta is: 
 [[2.88111888]
 [3.53379953]
 [1.04662005]]
